'use strict';
const {assert}=require('../_helpers.cjs');const {reducer,stateWith,submit,resolveAttack}=require('../_runtime_fixture.cjs');
function start(hand){const s=stateWith('S1-ARC-H001',['S1-WAR-H001','S1-WAR-H001','S1-WAR-H001']);s.phase='Deploy';s.players.P1.hand=hand.slice();return s;}
let s=start(['S1-ARC-013']);let r=reducer.submitIntent(s,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-013'});assert(r.errors.length>0,'Triple Shot must reject without Poison/Burning Arrow');
for(const hand of [['S1-ARC-013','S1-ARC-002'],['S1-ARC-013','S1-ARC-007'],['S1-ARC-013','S1-ARC-002','S1-ARC-007']]){let t=start(hand);r=reducer.submitIntent(t,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-013'});assert(!r.errors.length,'Triple Shot precheck should accept qualifying Hand');}
s=start(['S1-ARC-013','S1-ARC-002']);s=submit(s,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-013'});s=submit(s,{type:'SELECT_SOURCE',player_id:'P1',source_slot:'Center'});s=submit(s,{type:'CONFIRM_ACTION',player_id:'P1'});
let ts=s.players.P1.attachments.find(a=>a.card_id==='S1-ARC-013');assert(ts,'Triple Shot must enter Attachment Slot');assert(ts.lifecycle_mode==='while_present_in_attachment_slot','Triple Shot lifecycle must be attachment-presence based');assert(ts.remaining_count===null&&ts.turns_remaining===null,'Triple Shot must not have one-turn counter');assert(ts.tick_phase===null,'Triple Shot must not have End Phase expiry');assert(!('bound_card_id' in ts)&&!('selected_arrow' in ts),'Triple Shot runtime binding state must not exist');
s.players.P1.main_deck=['S1-ARC-002'];s.players.P2.main_deck=['S1-WAR-001'];s.phase='End';s=submit(s,{type:'NEXT_PHASE',player_id:'P1'});assert(s.players.P1.attachments.some(a=>a.card_id==='S1-ARC-013'),'Triple Shot must remain after End Phase');
// Force a future legal second-attack scenario and prove the same attachment still applies repeatedly.
s.active_player_id='P1';s.phase='Battle';s.players.P1.hand=['S1-ARC-002'];s.players.P1.board.Center.hero.exhausted=false;s=submit(s,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-002'});s=submit(s,{type:'SELECT_SOURCE',player_id:'P1',source_slot:'Center'});assert(s.pending.target_required===false&&s.pending.triple_shot_area===true,'qualifying arrow must become Area Attack through actual reducer');s=submit(s,{type:'CONFIRM_ACTION',player_id:'P1'});assert(s.pending_attack_resolution.action_profile==='Area Attack'&&s.pending_attack_resolution.targets.length===3,'Triple Shot must alter actual attack resolution');s=resolveAttack(s);assert(s.players.P1.attachments.some(a=>a.card_id==='S1-ARC-013'),'Triple Shot must not be consumed by first qualifying attack');
s.active_player_id='P1';s.phase='Battle';s.players.P1.hand=['S1-ARC-007'];s.players.P1.board.Center.hero.exhausted=false;s=submit(s,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-007'});s=submit(s,{type:'SELECT_SOURCE',player_id:'P1',source_slot:'Center'});assert(s.pending.target_required===false,'second qualifying attack must still receive Triple Shot');
// Removal immediately ends conversion.
s.pending=null;s.players.P1.hand=['S1-ARC-002'];s.players.P1.attachments=s.players.P1.attachments.filter(a=>a.card_id!=='S1-ARC-013');s.players.P1.board.Center.hero.exhausted=false;s=submit(s,{type:'PLAY_CARD',player_id:'P1',card_id:'S1-ARC-002'});s=submit(s,{type:'SELECT_SOURCE',player_id:'P1',source_slot:'Center'});assert(s.pending.target_required===true&&!s.pending.triple_shot_area,'removing Triple Shot must immediately end effect');
console.log('PASS Triple Shot integration through reducer');
