const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('js/app.bundle.js','utf8');
const css=fs.readFileSync('css/app.css','utf8');
assert(app.includes('<h1>DECK SETUP</h1>'));
assert(app.includes('class="setup-status-pill">NOT STARTED'));
assert(!app.includes('Select current Starter60 deck packages before creating a match.'));
assert(!app.includes('deck-builder-setup-note">Build or edit a deck'));
assert(!app.includes('class="deck-source"'));
assert(!app.includes('class="legacy-package-list"'));
assert(app.includes('class="deck-picker-row"'));
assert(app.includes('class="import-button"'));
assert(app.indexOf('id="openDeckBuilderButton"') < app.indexOf('id="resetDecks"'));
assert(css.includes('grid-template-columns:minmax(0,4fr) minmax(108px,1fr)'));
assert(css.includes('.deck-setup-actions .deck-builder-launch{display:none!important}'));
assert(css.includes('overflow-y:auto!important'));
assert(css.includes('aspect-ratio:63/88!important'));
assert(css.includes('.v96-app .card-played-panel'));
assert(css.includes('position:sticky!important'));
console.log('PASS VS AI v5.38 responsive UI locks.');
