const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('js/app.bundle.js','utf8');
const css=fs.readFileSync('css/app.css','utf8');
assert(app.includes("NON-SCRIPTED — TUTORIAL GAMEPLAY")&&app.includes("VS AI LOBBY"));
assert(!app.includes('class="setup-status-pill">NOT STARTED'));
assert(!app.includes('Select current Starter60 deck packages before creating a match.'));
assert(!app.includes('deck-builder-setup-note">Build or edit a deck'));
assert(!app.includes('class="deck-source"'));
assert(!app.includes('class="legacy-package-list"'));
assert(app.includes('class="deck-picker-row"'));
assert(app.includes('class="import-button"'));
assert(app.includes('id="startMatchButton"'));
assert(!app.includes('id="openDeckBuilderButton"')&&!app.includes('id="resetDecks"'));
assert(css.includes('grid-template-columns:minmax(0,4fr) minmax(108px,1fr)'));
assert(css.includes('overflow-y:auto!important'));
assert(css.includes('aspect-ratio:63/88!important'));
assert(css.includes('.v96-app .card-played-panel'));
assert(css.includes('position:sticky!important'));
console.log('PASS VS AI v5.52 responsive UI locks.');
