'use strict';
const ARBALEST_CLASSES=new Set(['arbalest','grand arbalest']);
function heroDisplayClass(card,hero){const i=card&&card.identity||{};return String(card&& (card.display_class||card.class_name||card.class)||i.display_class||i.class||hero&& (hero.display_class||hero.class_name||hero.class)||'').trim();}
function activeArbalestHeroes(player,cardResolver){const out=[];for(const slot of ['Left','Center','Right']){const ss=player&&player.board&&player.board[slot];const h=ss&&ss.slot_mode==='HERO'&&ss.hero&&!ss.hero.defeated?ss.hero:null;if(!h)continue;const c=cardResolver?cardResolver(h.card_id):null;if(ARBALEST_CLASSES.has(heroDisplayClass(c,h).toLowerCase()))out.push({slot,hero:h,card:c});}return out;}
function ensureDrawStats(player){if(!player.turn_stats)player.turn_stats={};if(player.turn_stats.actual_draws_this_turn===undefined)player.turn_stats.actual_draws_this_turn=0;if(player.turn_stats.cards_drawn_this_turn===undefined)player.turn_stats.cards_drawn_this_turn=0;return player.turn_stats;}
function commitActualDraw(player,count,cardResolver){const n=Math.max(0,Number(count||0));const stats=ensureDrawStats(player);stats.actual_draws_this_turn+=n;const active=activeArbalestHeroes(player,cardResolver);if(active.length)stats.cards_drawn_this_turn=Math.min(6,Number(stats.cards_drawn_this_turn||0)+n);return{actual_draws:n,arbalest_active:active.length>0,arbalest_draw_this_turn:stats.cards_drawn_this_turn};}
function resetTurnDrawStats(player){player.turn_stats={...(player.turn_stats||{}),actual_draws_this_turn:0,cards_drawn_this_turn:0};return player.turn_stats;}
function onRankUp(player,fromClass,toClass){const from=String(fromClass||'').toLowerCase(),to=String(toClass||'').toLowerCase();const stats=ensureDrawStats(player);if(from==='archer'&&to==='arbalest')stats.cards_drawn_this_turn=0;return stats.cards_drawn_this_turn;}
function isActualDrawMovement(movement){return Boolean(movement&&movement.from==='Main Deck'&&movement.to==='Hand'&&movement.top_of_main_deck===true&&movement.opening_hand!==true&&movement.search_add!==true&&movement.return_from_discard!==true);}
module.exports={ARBALEST_CLASSES,heroDisplayClass,activeArbalestHeroes,ensureDrawStats,commitActualDraw,resetTurnDrawStats,onRankUp,isActualDrawMovement};
