'use strict';
const ADDITIVE=new Set(['Poison','Burn','Freeze','Stun']);
function statusName(s){return String(s&& (s.status||s.name)||'');}
function duration(s){return Math.max(0,Number(s&& (s.duration_turns??s.duration??s.turns_remaining)||0));}
function mergeStatusList(statuses,statusEffect){const list=Array.isArray(statuses)?statuses.slice():[];const name=statusName(statusEffect);if(!name){list.push(statusEffect);return list;}const idx=list.findIndex(s=>statusName(s).toLowerCase()===name.toLowerCase());if(idx<0){list.push({...statusEffect,duration_turns:duration(statusEffect)});return list;}const old=list[idx],oldD=duration(old),newD=duration(statusEffect);const merged={...old,...statusEffect};merged.duration_turns=ADDITIVE.has(name)?oldD+newD:Math.max(oldD,newD);list[idx]=merged;return list;}
function applyStatusIfConnected(resolution,statusEffect,target){if(!resolution||!resolution.applySecondEffect)return{applied:false,reason:'Attack did not connect.'};const nextTarget=Object.assign({},target);nextTarget.statuses=mergeStatusList(nextTarget.statuses,statusEffect);return{applied:true,target:nextTarget};}
function hasStatus(statuses,name){const wanted=String(name||'').toLowerCase();return (Array.isArray(statuses)?statuses:[]).some(s=>statusName(s).toLowerCase()===wanted&&duration(s)>0);}
function heroStatusesFromSlot(slotState){return slotState&&slotState.slot_mode==='HERO'&&slotState.hero&&!slotState.hero.defeated?(slotState.hero.statuses||[]):[];}
function slotHasActiveStatus(slotState,name){return hasStatus(heroStatusesFromSlot(slotState),name);}
function movementBlockedByFreeze(board,firstSlot,secondSlot,source){const category=String(source||'').toLowerCase();if(!['manual','normal_reposition','skill','skill_effect'].includes(category))return{blocked:false};const first=board&&board[firstSlot],second=board&&board[secondSlot];const frozen=[];if(slotHasActiveStatus(first,'Freeze'))frozen.push(firstSlot);if(slotHasActiveStatus(second,'Freeze'))frozen.push(secondSlot);if(!frozen.length)return{blocked:false};return{blocked:true,code:category.startsWith('skill')?'FREEZE_BLOCKS_SKILL_MOVEMENT':'FREEZE_BLOCKS_NORMAL_REPOSITION',frozen_slots:frozen,errors:[category.startsWith('skill')?'Frozen Hero cannot change position through a Skill effect.':'Frozen Hero cannot participate in normal/manual Reposition.']};}
function dodgeBlockedByFreeze(slotState){return slotHasActiveStatus(slotState,'Freeze');}
module.exports={ADDITIVE,statusName,duration,mergeStatusList,applyStatusIfConnected,hasStatus,heroStatusesFromSlot,slotHasActiveStatus,movementBlockedByFreeze,dodgeBlockedByFreeze};
